services:
  - type: web
    name: voice-backend
    env: python
    rootDir: audio_app
    pythonVersion: 3.10.14
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port ${PORT}
